# Generated by Django 4.0.4 on 2022-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.ImageField(upload_to='')),
                ('details', models.TextField()),
                ('available', models.BooleanField()),
                ('catagory', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100)),
            ],
        ),
    ]
